- .dockerignore
- Dockerfile
- package-lock.json
> NCS-147 Adding Docker config

- Tiltfile.dev
Adding Tiltfile to run in Tilt
> NCS-147 Adding Tiltfile

- start.sh
> Adding start.sh script

- Makefile
- package-lock.json
- package.json
- sonar-project.properties
> NCS-119 Added Makefile

- routes.yaml
Adding the content for routes.yaml file
> NCS-119 Adding routes.yaml content

- start.sh
Fixing start.sh script, needs a command in the 'if then' block
> NCS-119 Fixing start.sh to get deployment working

- package-lock.json
- package.json
- test/controllers/index.controller.spec.unit.ts
NCS-117 Adding units test for index page
> NCS-117 adding units test for index page

- package-lock.json
- package.json
- src/app.ts
- src/controllers/start.controller.ts
- src/routes/routes.ts
- test/controllers/start.controller.spec.unit.ts
- views/layout.html
- views/start.html
NCS-45 adding the start page content.
> NCS-45 adding the start page content.

- views/start.html
Clean up the template for the start page.
> Start page cleanup

- src/app.ts
- src/controllers/company.number.controller.ts
- src/routes/routes.ts
- src/types/page.urls.ts
- test/controllers/company.number.controller.unit.ts
- views/start.html
Adding link to company number page.
> Ncs 46 added link to company number page

- package-lock.json
- package.json
- src/app.ts
- src/middleware/authentication.middleware.ts
> NCS-46 Add authentication check.

- src/app.ts
- test/controllers/company.number.controller.unit.ts
- test/controllers/start.controller.unit.ts
- test/middleware/authentication.middleware.unit.ts
- test/middleware/service.availability.middleware.unit.ts
- test/mocks/all.middleware.mock.ts
- test/mocks/authentication.middleware.mock.ts
- test/mocks/service.availability.middleware.mock.ts
- test/mocks/session.middleware.mock.ts
Adding missing tests and refactoring mocks and fixing the auth url mapping so that confirmation-statement/ no longer requires sign-in.
> NCS-46 Fix auth url mapping and update tests

- views/start.html
Adding an ID to the start-now button to help the automated tests identify it
> NCS-46 Adding id to start now button to help automated tests

- .githooks/pre-commit
Adding a githook to run lint:fix automatically whenever you commit
> Adding githook for lint

- README.md
Updated documentation for the project
> Readme details for project

- views/layout.html
> ncs-121 Add survey feedback link.

- src/controllers/company.number.controller.ts
- src/types/page.urls.ts
- test/controllers/company.number.controller.unit.ts
Making use of the company lookup module which will display the page for us.
> NCS-180 Redirecting to company lookup page

- src/app.ts
- src/controllers/error.controller.ts
- src/types/template.paths.ts
- test/controllers/error.controller.unit.ts
- views/page-not-found.html
Creation of page not found stop screen redirected from any unrecognised urls
> NCS-143 Create page not found screen

- views/page-not-found.html
Remove unused block and fix indentation on page not found html
> Remove unused block and fix indentation on page not found screen

- src/controllers/company.number.controller.ts
- src/middleware/authentication.middleware.ts
- src/routes/routes.ts
- src/types/page.urls.ts
- src/types/template.paths.ts
- test/middleware/authentication.middleware.unit.ts
- test/routes/routes.spec.unit.ts
- views/accessibility-statement.html
JIRA TICKET - [NCS-163](https://companieshouse.atlassian.net/browse/NCS-163) 
Added an accessbility statement page, whitelist function in authentication middleware and unit tests.
> Add accessibility statement page

- test/controllers/company.number.controller.unit.ts
- test/controllers/error.controller.unit.ts
- test/controllers/start.controller.unit.ts
- test/mocks/session.middleware.mock.ts
Moving ioredis mock out of controllers and into session middleware mock
> Moving ioredis mock into session middlewre mock

- src/controllers/confirm.company.controller.ts
- src/routes/routes.ts
- src/types/page.urls.ts
- src/types/template.paths.ts
- test/controllers/confirm.company.controller.unit.ts
- views/confirm-company.html
- views/layout.html
> ncs-59 Create confirm company page.

- package-lock.json
- views/confirm-company.html
- views/layout.html
Replacing the table element in the confirm company page with the summary list to match GDS requirements.
> NCS-57 Replacing govuk table with govuk summary list element

- package-lock.json
- package.json
- src/controllers/confirm.company.controller.ts
- src/services/company.profile.service.ts
- test/controllers/confirm.company.controller.unit.ts
- test/mocks/company.profile.mock.ts
- test/services/company.profile.service.unit.ts
- views/confirm-company.html
Populating confirm company page with Company Profile data
> NCS-89 Populating confirm company page with Company Profile data

- .gitmodules
- Makefile
NCS 89 adding api enumeration submodule to confirmation statement web
> NCS 89 adding api enumeration

- .dockerignore
- Dockerfile
- package-lock.json
- package.json
- src/services/company.profile.service.ts
- src/utils/api.enumerations.ts
- src/utils/date.formatter.ts
- test/mocks/company.profile.mock.ts
- test/services/company.profile.service.unit.ts
- test/utils/api.enumerations.unit.ts
- test/utils/date.formatter.unit.ts
Added API enumerations and date formatter for company profile page.
> Ncs 89 add api enumeration util

- views/service-offline.html
NCS 200 update content of service offline page
> Update content of service offline page

- src/controllers/confirm.company.controller.ts
- src/controllers/error.controller.ts
- src/types/template.paths.ts
- test/controllers/confirm.company.controller.unit.ts
- test/controllers/error.controller.unit.ts
- views/service-offline-mid-journey.html
Adding the error handler and error page. Not sure about the name of the template but kept it the same as per the prototype.
> NCS-201 Adding generic error handler and page

- views/confirm-company.html
matomo event tracking for choose another company link on confirm company page
> matomo event tracking for choose another company link 

- views/layout.html
- views/start.html
Changing the header link to go o the real https://www.gov.uk
> NCS-290 Fixing GovUk Header link

- src/controllers/start.controller.ts
- src/utils/properties.ts
- test/global.setup.ts
- views/start.html
add env variable for piwik start goal id
> add env variable for piwik start goal id

- package-lock.json
- src/controllers/confirm.company.controller.ts
- src/types/template.paths.ts
- test/controllers/confirm.company.controller.unit.ts
- views/use-webfiling.html
[NCS-127](https://companieshouse.atlassian.net/browse/NCS-127)
Add stop screen for companies that cannot use CHS service but can file through webfiling.
> Add stop screen for webfiling company types

- src/services/company.profile.service.ts
- test/services/company.profile.service.unit.ts
- views/confirm-company.html
[NCS-244](https://companieshouse.atlassian.net/browse/NCS-244)
Update the date and field name on confirm company page.
> Update the date on confirm company page

- views/check-trading-status.html
> NCS-234 Matomo trading status page

- views/confirm-company.html
Switched dates in template to be:
Date of next confirmation statement:  nextMadeUpTo
To be filed by: nextDue
> NCS-371 BUG confirm company dates wrong way around

- src/controllers/task.list.controller.ts
- test/controllers/task.list.controller.unit.ts
display correct filing date on task list page based on when user files in relation to their various due dates and the current system date
> Ncs 207 display filing date on task list page

- src/utils/api.enumerations.ts
- test/utils/api.enumerations.unit.ts
Discussed with analyst and decided that the content of company-type is what we require.
> NCS-267 Use company type

- views/paper-filing.html
[NCS-220](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=423&modal=detail&selectedIssue=NCS-220)
Add matomo tracking events to links on file on paper stop screen
> Add analytics to file on paper stop screen

- package-lock.json
- package.json
- src/controllers/task.list.controller.ts
- test/controllers/task.list.controller.unit.ts
Update displayed filing date based on changed acceptance criteria
> NCS-207 Update displayed filing date based on changed acceptance criteria

- views/confirm-company.html
[NCS-293](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=423&modal=detail&selectedIssue=NCS-293)
Add event tracking to confirm and contiue button in the confirm company page.
> Add event tracking to confirm and continue button

- src/controllers/trading.status.controller.ts
Noticed the trading status template doesn't use the tradingStatus = "0"; value passed to it anymore so I've removed it.
Refactored a small amount, made a couple of small functions for the url injecting as they were previously doing the same thing in both get and post
For a future PR I think i will create a "url util" module and move the url functions out from here into there, as inserting the company number into the url is going to be used in a lot of places in future.
> Trading status controller changes

- src/controllers/task.list.controller.ts
- test/controllers/task.list.controller.unit.ts
Fix lint complaints, update error handling when confirmationstatement is missing from company profile
> NCS-207 Fix lint complaints, update error handling when confirmationstatement is missing from company profile

- src/controllers/confirm.company.controller.ts
- src/controllers/task.list.controller.ts
- src/controllers/trading.status.controller.ts
- src/utils/url.ts
- test/utils/url.unit.ts
Created a utility function to populate the url with company number seeing as this is going to be done a lot.
> Creating a function to populate urls with company number in url utils

- src/controllers/confirm.sic.code.controller.ts
- src/controllers/tasks/confirm.sic.code.controller.ts
- src/routes/routes.ts
- src/types/sic.code.ts
- src/utils/api.enumerations.ts
- test/controllers/tasks/confirm.sic.code.controller.unit.ts
- test/utils/api.enumerations.unit.ts
- views/includes/sic/sic-details.html
[NCS-91](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-91), [NCS-77](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-77)
Get sic code data and display it in the sic code page.
> NCS-91, NCS-77 get and display sic code details

- views/tasks/sic.html
[NCS-231
](https://companieshouse.atlassian.net/browse/NCS-231)
Add data events to links and buttons on the sic code page.
> Add data events to sic code page

- src/controllers/tasks/confirm.sic.code.controller.ts
- src/routes/routes.ts
- src/types/template.paths.ts
- test/controllers/tasks/confirm.sic.code.controller.unit.ts
- views/incorrect-information/wrong-sic.html
stop page for incorrect sic code navigated by selecting NO radio button on sic code page
> NCS 136 sic code stop page

- src/controllers/tasks/confirm.sic.code.controller.ts
- src/utils/constants.ts
- test/controllers/tasks/confirm.sic.code.controller.unit.ts
- views/tasks/sic.html
Add navigation to task list page.
Also added error message when no selection is made.
> NCS-64 Add Sic code page navigation to task list page.

- views/incorrect-information/wrong-sic.html
[NCS-436](https://companieshouse.atlassian.net/browse/NCS-436)
Add matomo analytics to the webfiling service link and back link.
> Add matomo to links in SIC stop page

- src/controllers/tasks/registered.office.address.controller.ts
- test/controllers/tasks/registered.office.address.controller.unit.ts
- views/includes/roa.html
> NCS-48 Display registered office address.

- src/services/company.officers.service.ts
Change logging to info for testers to view company officer retrieval in test environments
> update to log when retrieving company officers

- src/controllers/tasks/registered.office.address.controller.ts
- src/routes/routes.ts
- src/utils/constants.ts
- test/controllers/tasks/registered.office.address.controller.unit.ts
- views/tasks/registered-office-address.html
[NCS-61](https://companieshouse.atlassian.net/browse/NCS-61)
Added navigation for radio buttons used in the registered office address page.
> NCS-61 Add navigation for roa radio buttons

- views/layout.html
> NCS-448 Jquery update

- package-lock.json
- views/includes/officers-styles.html
- views/includes/officers.html
- views/tasks/active-officers.html
[NCS-95](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-95)
Create the officer page
> NCS-95 create officers page

- views/includes/officers-styles.html
- views/includes/officers.html
[NCS-95](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?modal=detail&projectKey=BI&rapidView=234&selectedIssue=NCS-95)
Remove line under the last row of the summery list.
> NCS-95 Fix: Remove line under the last row

- views/tasks/active-officers.html
[NCS-439](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-439)
Add events ids to the radio button on the officers page.
> NCS-439 Add analytics to the radio buttons

- test/controllers/create.transaction.controller.unit.ts
Adding unit test to cover error/exception handling in create transaction controller
> NCS-449 Adding unit test to cover error in create transaction controller

- src/controllers/tasks/shareholders.controller.ts
- src/routes/routes.ts
- src/types/page.urls.ts
- src/types/task.list.ts
- src/types/template.paths.ts
- test/controllers/tasks/shareholders.controller.unit.ts
- views/includes/shareholders-styles.html
- views/includes/shareholders.html
- views/includes/task-list/people.html
- views/tasks/shareholders.html
[NCS-72
](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-72)
Create the shareholders page.
> NCS-72 Create the shareholders page

- views/tasks/shareholders.html
[NCS-72](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-72)
Add third radio button on the shareholders html page.
> NCS-72 Refactor

- views/tasks/shareholders.html
Reverts companieshouse/confirmation-statement-web#192
> Revert "NCS-72 Refactor"

- src/controllers/tasks/shareholders.controller.ts
- src/routes/routes.ts
- src/utils/constants.ts
- test/controllers/tasks/shareholders.controller.unit.ts
- views/tasks/shareholders.html
[NCS-73](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-73)
Add navigation to the shareholders page
> Ncs 73 add navigation to shareholders page

- views/tasks/shareholders.html
[NCS-73](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-73)
Uncheck checked radio button
> NCS-73 Refactor

- test/controllers/task.list.controller.unit.ts
- test/mocks/task.list.mock.ts
Updating task list controller test to use a mocked task list instead of calling the real initTaskList function
> NCS-480 Updating task list controller test to use a mocked task list

- package-lock.json
- package.json
Did a npm uninstall prior to npm i
> NCS-480 Updating to use latest 1.33 private-api-sdk-node

- src/controllers/tasks/active.officers.controller.ts
- src/utils/constants.ts
- test/controllers/tasks/active.officers.controller.unit.ts
Fix the broken navigation links on the page.
Fix the page details that were disappearing on errorMessage page render.
> NCS-535 Fix: Active officer details page broken back button

- views/includes/officers.html
- views/includes/shareholders.html
[NCS-554](https://companieshouse.atlassian.net/browse/NCS-554)
Remove no-border command to show the borders for the summary list.
> NCS-554 Amend summary list to show border

- src/controllers/tasks/people.with.significant.control.controller.ts
- src/utils/date.ts
- test/controllers/tasks/people.with.significant.control.controller.unit.ts
- test/utils/date.unit.ts
- views/tasks/includes/normal-psc.html
Adding psc date to psc page and created a new formatter for just month and year (currently chs style dob's have only month and year)
> NCS-570 Adding formatted Psc DOB to psc page

- src/controllers/tasks/confirm.sic.code.controller.ts
- src/services/task.list.service.ts
- src/types/sic.code.ts
- test/controllers/tasks/confirm.sic.code.controller.unit.ts
- test/services/task.list.service.unit.ts
[NCS-360](https://companieshouse.atlassian.net/browse/NCS-360)
Update the tag in task list page according to the data from the database.
> NCS-360 save sic code data to database

- src/controllers/tasks/registered.office.address.controller.ts
- test/controllers/tasks/registered.office.address.controller.unit.ts
submit ROA data to post CS update after review ROA details page
> NCS 377 save ROA data

- src/services/task.list.service.ts
- test/services/task.list.service.unit.ts
- views/includes/task-list/addresses.html
NCS 248 Display completion status of ROA on task list page
> NCS 248 Display completion status of ROA on task list page

- test/controllers/tasks/people.with.significant.control.controller.unit.ts
- views/tasks/includes/relevant-legal-entity.html
Populating rle template with the psc data
> Ncs 553 add rle data to psc page

- views/includes/statement-of-capital.html
[NCS-487](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-487)
Add missing row to the statement of capital page.
> NCS-487 Amend statement of capital page

- src/controllers/tasks/psc.statement.controller.ts
- src/utils/api.enumerations.ts
- test/controllers/tasks/psc.statement.controller.unit.ts
- test/utils/api.enumerations.unit.ts
Updating psc statements to get the description from api enumerations
> NCS-178 Get Psc Statement from api enumeration

- package.json
- src/controllers/tasks/active.directors.controller.ts
- src/services/task.list.service.ts
- test/controllers/tasks/active.directors.controller.unit.ts
- test/services/task.list.service.unit.ts
- views/includes/task-list/people.html
Directors details section save section status and display section status on task list
> ncs 411 and 96 - Directors details section save/display section status

- package-lock.json
add missing package-lock upgrade
> add missing package-lock upgrade

- package-lock.json
- package.json
- src/controllers/tasks/people.with.significant.control.controller.ts
- test/controllers/tasks/people.with.significant.control.controller.unit.ts
- test/mocks/person.of.significant.control.mock.ts
- views/tasks/includes/normal-psc.html
- views/tasks/includes/relevant-legal-entity.html
Updated to use the latest private sdk that includes making the PSC fields optional
> NCS-608 Updated to use lates private sdk with optional PSC fields

- package-lock.json
- package.json
- src/controllers/tasks/shareholders.controller.ts
- src/services/shareholder.service.ts
- test/controllers/tasks/shareholders.controller.unit.ts
- test/mocks/shareholder.mock.ts
- test/services/shareholder.service.unit.ts
- views/includes/shareholders.html
[NCS-81](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-81)
Display shareholders data in the shareholder page.
> NCS-81 Display shareholder data

- views/includes/shareholders.html
Amend variable for shareholders forename
> NCS-81 Use correct variable name for shareholder

- src/utils/update.confirmation.statement.submission.ts
lint was throwing no-case-declarations errors in src/utils/update.confirmation.statement.submission.ts- this should fix them
> Fixing lint violations on case statement

- src/controllers/tasks/register.locations.controller.ts
- src/routes/routes.ts
- src/types/template.paths.ts
- src/utils/constants.ts
- test/controllers/tasks/register.locations.controller.unit.ts
- views/incorrect-information/wrong-registers.html
- views/incorrect-information/wrong-shareholders.html
- views/tasks/register-locations.html
[NCS-75](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-75)
Add radio button functionaility, error message and stop screen.
> NCS-75 register location page navigation

- views/tasks/register-locations.html
[NCS-82](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-82)
> NCS-82 Add event log for registers page

- views/incorrect-information/wrong-registers.html
[NCS-461](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-461)
> NCS-461 Add analytics to wrong registers page

- test/services/payment.service.unit.ts
Adding tests for payment service
> NCS-641 Unit tests for payment service

- package-lock.json
- package.json
- test/services/payment.service.unit.ts
Updating tests after merge from main and adding types for UUID (VSCode highlighted it as types not found)
> NCS-641 Updating payment service tests and adding UUID types

- test/controllers/review.controller.unit.ts
- test/mocks/payment.mock.ts
- test/services/payment.service.unit.ts
Updating tests for review.controller post function
> NCS-641 Updating tests for review.controller

- package-lock.json
- package.json
- src/controllers/tasks/register.locations.controller.ts
- src/services/register.location.service.ts
- src/utils/format.ts
- test/controllers/tasks/register.locations.controller.unit.ts
- test/mocks/register.location.mock.ts
- test/services/register.location.service.unit.ts
- views/tasks/includes/register.html
fetch and display register location data on the register location page
> NCS 338 display register location data

- views/review.html
Formatting second date on the review page as it was missed on the last PR
> NCS-658 formatting additional review page date

- package-lock.json
- package.json
- src/controllers/tasks/register.locations.controller.ts
- src/services/task.list.service.ts
- src/utils/constants.ts
- src/utils/update.confirmation.statement.submission.ts
- test/controllers/tasks/register.locations.controller.unit.ts
- test/services/task.list.service.unit.ts
- test/utils/update.confirmation.statement.submission.unit.ts
- views/includes/task-list/addresses.html
save and display register location section status
> Ncs 283 save and display register location section status

- src/controllers/tasks/statement.of.capital.controller.ts
- test/controllers/tasks/statement.of.capital.controller.unit.ts
- views/tasks/statement-of-capital.html
Validate the Statement-Of-Capital share total number against the shareholders' total shares.
> NCS-497 statement-of-capital shares total validation

- views/incorrect-information/wrong-registers.html
amend register location stop screen, removing the "your filings" sentence and link
> ncs-663 - amend register location stop screen

- src/controllers/tasks/statement.of.capital.controller.ts
- test/controllers/tasks/statement.of.capital.controller.unit.ts
- views/incorrect-information/wrong-statement-of-capital.html
Fix navigation so the user goes to the stop-page and not the task-list page.
> NCS-497 Fix navigation to stop-page not task-list.

- test/mocks/active.director.details.mock.ts
- test/mocks/task.list.mock.ts
fixing warnings in the tests - you can see here - https://ci.platform.aws.chdev.org/teams/team-toro-loco/pipelines/confirmation-statement-web/jobs/build-test-analyse/builds/274#L610ea7d4:149
> Fixing warning messages that appear when running tests

- views/incorrect-information/wrong-ro.html
amend ro stop screen, remove your filings sentence and link
> ncs-664 - Amend ro stop screen, remove your filings sentence and link

- src/services/task.list.service.ts
- src/types/task.list.ts
- test/mocks/task.list.mock.ts
- test/services/task.list.service.unit.ts
isVisible on task list is redundant so removing it.
> Removing redundant isVisible from taskList

- src/controllers/tasks/register.locations.controller.ts
- src/utils/constants.ts
allows data to persist when page throws error from no radio button being selected
> add register location data to session 

- test/controllers/task.list.controller.unit.ts
Fixing the test for error being thrown on get, it failed when run on it's own due to mocks not being cleared.
Added missing tests to cover the post function.
> Updating task.list.controller tests

- src/controllers/tasks/statement.of.capital.controller.ts
- test/controllers/tasks/statement.of.capital.controller.unit.ts
- views/incorrect-information/wrong-statement-of-capital.html
- views/tasks/statement-of-capital.html
Validate statement-of-capital totalAmountUnpaidForCurrency by checking that it is not NULL.
> NCS-646 Add validation check for statement-of-capital totalAmountUnpaid.

- src/utils/format.ts
- test/mocks/active.director.details.mock.ts
- views/includes/directors.html
remove spacing and change case of officer surname on director details page
> officer details bug fix

- package-lock.json
- package.json
- src/controllers/tasks/shareholders.controller.ts
- src/controllers/tasks/statement.of.capital.controller.ts
- src/utils/update.confirmation.statement.submission.ts
- test/utils/update.confirmation.statement.submission.unit.ts
Using latest SDK to make data block in cs submission mandatory.
Updating test for this including removing some tests for optional data ( as no longer optional)
> NCS-681 Making data on submission mandatory

- src/controllers/trading.status.controller.ts
- src/utils/constants.ts
- src/utils/update.confirmation.statement.submission.ts
- test/controllers/trading.status.controller.unit.ts
- test/utils/update.confirmation.statement.submission.unit.ts
[NCS-345](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=NCS&modal=detail&selectedIssue=NCS-345)
Save yes or no answer for trading status to the database.
> NCS-345 Save trading status answer

- src/controllers/tasks/registered.office.address.controller.ts
- src/utils/format.ts
- src/utils/task/task.counter.ts
- src/utils/task/task.state.mapper.ts
- test/controllers/confirm.company.controller.unit.ts
- test/controllers/tasks/active.directors.controller.unit.ts
- test/controllers/tasks/confirm.sic.code.controller.unit.ts
- test/controllers/tasks/people.with.significant.control.controller.unit.ts
- test/controllers/tasks/psc.statement.controller.unit.ts
- test/controllers/tasks/register.locations.controller.unit.ts
Moving more modules to use the public api sdk instead of the private one
> Migrating more modules to use public sdk

- src/services/api.service.ts
- test/controllers/tasks/registered.office.address.controller.unit.ts
- test/controllers/tasks/statement.of.capital.controller.unit.ts
- test/mocks/active.director.details.mock.ts
- test/mocks/person.of.significant.control.mock.ts
- test/mocks/register.location.mock.ts
- test/services/api.service.unit.ts
- test/services/task.list.service.unit.ts
- test/utils/format.unit.ts
- test/utils/task/task.counter.unit.ts
- test/utils/task/task.state.mapper.unit.ts
Removing more usages of private-api-sdk-node
Removed teh private OAuth api client from api service as it's no longer needed
> Removing more usages of private-api-sdk-node

- views/start.html
> ncs-80 - amend start page

- test/mocks/confirmation.statement.submission.mock.ts
- test/services/task.list.service.unit.ts
- test/utils/task/task.counter.unit.ts
- test/utils/update.confirmation.statement.submission.unit.ts
updating some tests to get rid of warnings
> Updating tests to resolve warnings

- views/includes/task-list/addresses.html
- views/includes/task-list/nature-of-business.html
- views/includes/task-list/people.html
> NCS-424 - add matomo to task list page

- package-lock.json
- package.json
- src/controllers/trading.status.controller.ts
- src/utils/update.confirmation.statement.submission.ts
- test/controllers/trading.status.controller.unit.ts
- test/utils/update.confirmation.statement.submission.unit.ts
[NCS-689](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-689)
Add new function for sending trading status answer to the database
> NCS-689 Amend trading status data

- test/controllers/tasks/statement.of.capital.controller.unit.ts
- views/includes/statement-of-capital.html
Also add 'Total value' as a product of '**_Number of shares_**' and '**_Value of each share_**'.
> NCS-458 Statement-Of-Capital layout update to prototype v9

- src/controllers/tasks/shareholders.controller.ts
- src/controllers/tasks/statement.of.capital.controller.ts
- test/controllers/tasks/shareholders.controller.unit.ts
- test/controllers/tasks/statement.of.capital.controller.unit.ts
[NCS-684](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-684)
Fix - Display soc and shareholder data upon page reload.
> NCS-684 display soc and shareholder data

- views/review.html
[NCS-711](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-711)
Add new goals for confirm and pay, and confirm and submit button on the review page.
> NCS-711 matamo goals for review page

- package-lock.json
- package.json
- src/controllers/tasks/people.with.significant.control.controller.ts
- src/utils/format.ts
- test/controllers/tasks/people.with.significant.control.controller.unit.ts
- views/tasks/includes/normal-psc.html
> Ncs 323 display psc service address

- package-lock.json
- package.json
- src/controllers/tasks/people.with.significant.control.controller.ts
- src/utils/format.ts
reorder address format on psc screen
> ncs-323 - reorder address format on psc screen

- package-lock.json
- package.json
- src/utils/format.ts
- test/controllers/tasks/people.with.significant.control.controller.unit.ts
- views/tasks/includes/relevant-legal-entity.html
[NCS-619
](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&modal=detail&selectedIssue=NCS-619)
Add register location field and amend the fields name and order.
> NCS-619 - Amend psc fields

- package-lock.json
- package.json
- test/controllers/tasks/active.directors.controller.unit.ts
- test/mocks/active.director.details.mock.ts
- views/includes/directors.html
add Appointment date to officer details page
> add Appointment date to officer details page

- src/controllers/tasks/active.directors.controller.ts
- views/includes/directors.html
Format title case of country of residence
> ncs-724 - Format title case of country of residence

- package-lock.json
- package.json
- src/controllers/tasks/shareholders.controller.ts
- src/controllers/tasks/statement.of.capital.controller.ts
- src/services/shareholder.service.ts
- test/services/shareholder.service.unit.ts
[NCS-761](https://companieshouse.atlassian.net/browse/NCS-761)
Change shareholde function to use transactions to retrieve shareholder data since the endpoint is changed.
> NCS-761 Change shareholder endpoint

- views/tasks/register-locations.html
- views/tasks/shareholders.html
fix continue buttons on shareholders and register-locations pages
> ncs-817 - fix continue buttons on shareholders and register-locations pages

- src/controllers/tasks/natural.person.secretaries.controller.ts
- src/services/task.list.service.ts
- test/controllers/tasks/natural.person.secretaries.controller.unit.ts
> fix lint complaints

- views/layout.html
- views/trading-stop.html
implement matomo tracking on trading status stop screen webfiling link and feedback banner
> BI-9485-9486 - implement matomo tracking on trading status stop screen webfiling link and feedback banner

- package-lock.json
- package.json
- test/mocks/active.director.details.mock.ts
Upgrade api-sdk-node version to latest with the updated ActiveOfficerDetails.
> BI-9482 Update ActiveOfficerDetails object

- views/tasks/active-officers.html
- views/tasks/people-with-significant-control.html
- views/tasks/psc-statement.html
- views/tasks/register-locations.html
- views/tasks/registered-office-address.html
- views/tasks/statement-of-capital.html
Updated the text and labels where applicable. As the ticket refers specifically to what is displayed I have kept the ids and values as they are.
> BI-9577 update no but button

- src/controllers/tasks/active.officers.details.controller.ts
- src/controllers/tasks/natural.person.secretaries.controller.ts
trying to reduce the sonar complexity rating
> NCS-9488 Update controllers to reduce Sonar complexity rating

- views/use-webfiling.html
Requested updates and fixes for this stop page.
> BI-9606 update errors on webfiling top page

- package-lock.json
- package.json
Updated api sdk node dependency.
> BI-9870 package json updated to get new sdk node

- src/utils/constants.ts
- test/controllers/tasks/active.directors.controller.unit.ts
Updating the officer details stop page title to 'Incorrect Officer Details'
> BI-9954 Update officer details stop page title

- test/controllers/confirm.company.controller.unit.ts
- views/invalid-company-status.html
Updating page title on stop screen for invalid company status
> BI-9954 Update invalid company status stop screen page title

- views/use-webfiling.html
Updated first sentence.
Add company secretary to bullet points.
Changed director to officer in bullet points.
> BI-10068 display updated text on stop page

- test/controllers/tasks/active.officers.details.controller.unit.ts
* Re-included one test when service throws an error
* Removed test for officer type list check that is no longer relevant
> BI-10142 Tests for error scenarios

- src/controllers/tasks/active.officers.details.controller.ts
- test/controllers/tasks/active.officers.details.controller.unit.ts
- test/mocks/active.officers.details.mock.ts
Adjusted test data as each value needs to be unique to each officer.
> BI-10150 Extract natural non corporate director data

- src/controllers/tasks/active.officers.controller.ts
- src/utils/constants.ts
* Content changed to reference more general 'officer' and not 'director'
> BI-10189 Amendment to existing officer stop screen

- views/incorrect-information/wrong-statement-of-capital.html
Removed else clause as the text is the same in both of the previous conditions.
> BI-10411 Display correct text on Statement of capital stop screen

- views/start.html
* 3rd bullet point text updated
* 4th bullet point text NOT updated (already correct)
> BI-9917 Amendment of text on start screen

- test/controllers/incorrect-information/wrong.sic.controller.unit.ts
Updating unit test for wrong.sic.controller for backlink
> BI-10486 Updating wrong.sic.controller unit test

- src/middleware/company.authentication.middleware.ts
- src/validators/company.number.validator.ts
- src/validators/is.psc.validator.ts
- src/validators/radio.button.validator.ts
* Log reason for failure in validators if multiple reasons are possible
* Use same error logging approach (and return code) in the authentication middleware
> BI-10602 Improvements to logging of validation failures

- src/validators/company.number.validator.ts
- test/validators/company.number.validator.unit.ts
Changed validation criteria to include IP companies.
> Bi 10714 wrong stop screen for company

- src/controllers/incorrect-information/wrong.officer.details.controller.ts
- src/controllers/incorrect-information/wrong.psc.details.controller.ts
- src/controllers/incorrect-information/wrong.psc.statement.controller.ts
- src/controllers/tasks/people.with.significant.control.controller.ts
- src/utils/constants.ts
- test/controllers/incorrect-information/wrong.officer.details.controller.unit.ts
- test/controllers/incorrect-information/wrong.psc.details.controller.unit.ts
- test/controllers/incorrect-information/wrong.psc.statement.controller.unit.ts
- test/controllers/tasks/people.with.significant.control.controller.unit.ts
- views/incorrect-information/wrong-details.html
- views/incorrect-information/wrong-registers.html
- views/incorrect-information/wrong-ro.html
Changed the wrong registers, wrong RO address, and wrong details (officers and psc) screen.
[BI-10583](https://companieshouse.atlassian.net/browse/BI-10583)
[BI-10584](https://companieshouse.atlassian.net/browse/BI-10584)
[BI-10591](https://companieshouse.atlassian.net/browse/BI-10591)
[BI-10592](https://companieshouse.atlassian.net/browse/BI-10592)
> Altered Confirmation Statement stop screens

- test/controllers/incorrect-information/wrong.registers.controller.unit.ts
- views/incorrect-information/wrong-registers.html
Correction to the text for wrong register stop screen to match the prototype.
> Correction to the wrong register stop screen.

- src/controllers/incorrect-information/wrong.officer.details.controller.ts
- src/controllers/incorrect-information/wrong.psc.details.controller.ts
- src/controllers/incorrect-information/wrong.psc.statement.controller.ts
- src/controllers/incorrect-information/wrong.registered.office.address.controller.ts
- src/controllers/incorrect-information/wrong.registers.controller.ts
- src/routes/routes.ts
- src/utils/constants.ts
- src/utils/wrong.information.stop.screen.common.web.calls.ts
- test/controllers/incorrect-information/wrong.officer.details.controller.unit.ts
- test/controllers/incorrect-information/wrong.psc.details.controller.unit.ts
- test/controllers/incorrect-information/wrong.psc.statement.controller.unit.ts
- test/controllers/incorrect-information/wrong.registered.office.address.controller.unit.ts
- test/controllers/incorrect-information/wrong.registers.controller.unit.ts
- views/includes/error-alert-message.html
- views/incorrect-information/wrong-details.html
- views/incorrect-information/wrong-registers.html
- views/incorrect-information/wrong-ro.html
Upon submission displays alert message when the radio buttons are not selected, and updates relevant records when the buttons are selected.
[BI-11032](https://companieshouse.atlassian.net/browse/BI-11032)
[BI-11102](https://companieshouse.atlassian.net/browse/BI-11102)
[BI-11108](https://companieshouse.atlassian.net/browse/BI-11108)
[BI-11110](https://companieshouse.atlassian.net/browse/BI-11110)
[BI-11113](https://companieshouse.atlassian.net/browse/BI-11113)
> Adding functionality & validation for stop screen radio buttons 

- src/controllers/incorrect-information/wrong.officer.details.controller.ts
- src/controllers/incorrect-information/wrong.psc.details.controller.ts
- src/controllers/incorrect-information/wrong.psc.statement.controller.ts
- src/controllers/incorrect-information/wrong.registered.office.address.controller.ts
- src/controllers/incorrect-information/wrong.registers.controller.ts
- views/includes/error-alert-message.html
- views/incorrect-information/wrong-details.html
- views/incorrect-information/wrong-registers.html
- views/incorrect-information/wrong-ro.html
Moved condition check away from alert fragment to main html.
[BI-11032](https://companieshouse.atlassian.net/browse/BI-11032)
> Fixing issues with stop screen radio button alerts

- src/controllers/incorrect-information/wrong.psc.statement.controller.ts
- test/controllers/incorrect-information/wrong.officer.details.controller.unit.ts
- test/controllers/incorrect-information/wrong.psc.details.controller.unit.ts
- test/controllers/incorrect-information/wrong.psc.statement.controller.unit.ts
- test/controllers/incorrect-information/wrong.registered.office.address.controller.unit.ts
- test/controllers/incorrect-information/wrong.registers.controller.unit.ts
[BI-11151](https://companieshouse.atlassian.net/browse/BI-11151)
Added a back button method in the psc statement stop screen controller which generates the back button based on whether there are PSCs present or not.
> Fix the back link from the PSC Statement stop screen

- test/controllers/incorrect-information/wrong.sic.controller.unit.ts
- test/controllers/task.list.controller.unit.ts
- views/includes/task-list/people.html
- views/incorrect-information/wrong-sic.html
- views/task-list.html
- views/tasks/psc-statement.html
- views/tasks/sic.html
[BI-10803] - https://companieshouse.atlassian.net/browse/BI-10803
[BI-10804] - https://companieshouse.atlassian.net/browse/BI-10804
[BI-10805]- https://companieshouse.atlassian.net/browse/BI-10805
[BI-10812] - https://companieshouse.atlassian.net/browse/BI-10812
[BI-10803]: https://companieshouse.atlassian.net/browse/BI-10803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BI-10804]: https://companieshouse.atlassian.net/browse/BI-10804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BI-10805]: https://companieshouse.atlassian.net/browse/BI-10805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BI-10812]: …
> Content changes for confirmation statement part 1

- test/controllers/tasks/people.with.significant.control.controller.unit.ts
- test/controllers/tasks/register.locations.controller.unit.ts
- test/controllers/trading.stop.controller.unit.ts
- views/includes/psc-details.html
- views/tasks/active-psc-details.html
- views/tasks/includes/register.html
- views/tasks/people-with-significant-control.html
- views/trading-stop.html
Changes to contents in multiple confirmation-statement screens and associated unit tests.
[BI-10806](https://companieshouse.atlassian.net/browse/BI-10806)
[BI-10808](https://companieshouse.atlassian.net/browse/BI-10808)
[BI-10810](https://companieshouse.atlassian.net/browse/BI-10810)
> Content changes for confirmation statement part 2

- views/incorrect-information/wrong-sic.html
- views/trading-stop.html
Updated the SIC codes and Trading status stop screens as per new instructions.
[BI-10805](https://companieshouse.atlassian.net/browse/BI-10805)
[BI-10806](https://companieshouse.atlassian.net/browse/BI-10806)
> Changes to SIC and Trading status stop screens

- views/incorrect-information/wrong-statement-of-capital.html
Changed content on incorrect statement of capital screen to remove. 
- Removed 'our' from link text
- Added 'opens in new tab'
[BI-11280](https://companieshouse.atlassian.net/browse/BI-11280)
> Content change - Incorrect statement of capital screen.

- views/task-list.html
Task status 'In progress' changed to 'Ready to continue'
[BI-11303](https://companieshouse.atlassian.net/browse/BI-11303)
> Changed status 'In progress' to 'Ready to continue'

- src/controllers/incorrect-information/wrong.sic.controller.ts
- src/controllers/tasks/statement.of.capital.controller.ts
fix 2 missed templates of https://github.com/companieshouse/confirmation-statement-web/pull/614
which Resolves:
https://companieshouse.atlassian.net/browse/BI-11403
> Add 2 missed places of PR614

- src/controllers/incorrect-information/wrong.statement.of.capital.controller.ts
fix 1 missed templates of https://github.com/companieshouse/confirmation-statement-web/pull/614
which Resolves:
https://companieshouse.atlassian.net/browse/BI-11403
> add 1 missed place in PR614

- src/controllers/signout.controller.ts
- views/includes/signout-bar.html
- views/signout.html
- Emit 'signout' event when user clicks 'signout' in the signout bar
- Emit 'signout-yes' event when the user selects 'yes' on the signout screen
- Emit 'signout-no' event when the user selects 'no' on the signout screen
> Added motomo tracking events to signout links

- src/app.ts
Bland commit to help run pipeline job for `main_legacy` branch
> Chore: Terminate statement correctly

- src/controllers/review.controller.ts
- src/controllers/task.list.controller.ts
- src/utils/date.ts
- src/utils/feature.flag.ts
- src/utils/update.confirmation.statement.submission.ts
- test/controllers/review.controller.unit.ts
- test/controllers/tasks/confirm.email.address.controller.unit.ts
- test/mocks/session.middleware.mock.ts
- test/utils/date.unit.ts
- test/utils/feature.flag.unit.ts
- views/layout.html
- views/review.html
https://companieshouse.atlassian.net/browse/ECCT-616
1. Add two new checkboxes for the following statements:
Confirmation Statement Text
Lawful Activity Statement Text
2. Centralise existing ECCT Day One code so it can be used in multiple places.
3. Added new unit tests for the centralised ecct code as well as add new unit tests for the updated review controller and web html page.
> add two new checkboxes with accompanying html text, centralise common ecct function

- terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
Reverts companieshouse/confirmation-statement-web#715
> Revert "Temporary edit to test offline error page"

- package-lock.json
Resolves `follow-redirects` vulnerability
> Chore: Resolve vulnerability

- package-lock.json
- test/services/eligibility.service.unit.ts
Just ran npm audit fix
Only manual edit was test-code-only whitespace tweak to fix linter issue
> Update express to fix security warning

- package-lock.json
Changes generated by running 'npm audit fix'
> Axios upgrade to address vulnerability

- src/app.ts
- views/check-trading-status.html
- views/confirm-company.html
- views/includes/csrf_token.html
- views/incorrect-information/wrong-officers.html
- views/incorrect-information/wrong-psc-details.html
- views/incorrect-information/wrong-registered-office-address.html
- views/incorrect-information/wrong-registers.html
- views/incorrect-information/wrong-shareholders.html
- views/incorrect-information/wrong-sic.html
- views/incorrect-information/wrong-statement-of-capital.html
- views/review.html
- views/tasks/active-officers-details.html
- views/tasks/active-officers.html
- views/tasks/active-psc-details.html
- views/tasks/check-email-address.html
- views/tasks/confirm-email-address.html
- views/tasks/people-with-significant-control.html
- views/tasks/provide-email-address.html
- views/tasks/psc-statement.html
- views/tasks/register-locations.html
- views/tasks/registered-office-address.html
- views/tasks/shareholders.html
- views/tasks/sic.html
- views/tasks/statement-of-capital.html
Added csrf to all forms except:
- signout
- trading-stop (you cannot use this service)
> SEC-113 Implement csrf token on forms where data is submitted

- views/signout.html
- views/trading-stop.html
https://companieshouse.atlassian.net/browse/SEC-113
Only 2 of 3 pages could be updated. Can add csrf to:
- sign out
- trading stop
but not to
- task list
as there is no form on this page. To add csrf we would have to change this page by adding a form.
> SEC-113 Two more pages require csrf

- package-lock.json
- package.json
- src/app.ts
Ticket:
https://companieshouse.atlassian.net/browse/CSE-660
Changes:
- Update govuk-frontend to 5.10.2 version
> CSE-660: upgrade the govuk frontend library to 5.10.2

- test/controllers/lp.start.controller.unit.ts
- views/limited-partners/layouts/layout.njk
- views/limited-partners/partials/banners/header-banner.njk
- views/limited-partners/partials/banners/instruction-banner.njk
- views/limited-partners/partials/footer.njk
- views/limited-partners/partials/header.njk
- views/limited-partners/partials/nav/signout-link.njk
moved javascript css into header so it will not need to be imported on every page. Style updated to remove issue with background colour bleed. Tests for landing page updated.
> Updates for css

- views/limited-partners/components/before-you-file/before-you-file.njk
- views/limited-partners/components/index/lp-start.njk
- views/limited-partners/layouts/layout.njk
- views/limited-partners/partials/footer.njk
- views/limited-partners/partials/header.njk
- views/limited-partners/partials/meta_header.njk
CSE-560 - Extending govuk template.njk, and now initAll() function operates correctly
> CSE-560 - Extending govuk template.njk, and now initAll() function operates correctly

- src/controllers/before.you.file.controller.ts
- src/controllers/lp.start.controller.ts
- src/routes/routes.ts
- test/controllers/lp.start.controller.unit.ts
- views/limited-partners/components/before-you-file/before-you-file.njk
- views/limited-partners/components/index/lp-start.njk
- views/limited-partners/partials/csrf-token.njk
- views/limited-partners/partials/nav/back-link.njk
Routing added for landing screen to before you file screen. Template has been left in place to be updated when next screen is created. Back button spacing fixed. 
https://github.com/user-attachments/assets/998e2e70-1d5a-438f-85d3-828b7a5da39b
> CSE-622 Set up routing

- src/controllers/before.you.file.controller.ts
- src/controllers/lp.before.you.file.controller.ts
- views/limited-partners/components/before-you-file/before-you-file.njk
- views/limited-partners/components/index/lp-start.njk
Validation for Before you file page. 
https://companieshouse.atlassian.net/browse/CSE-708
https://github.com/user-attachments/assets/6f8055fe-620d-4646-a15f-8ac89e06a370
> Cse 708 error validation

- locales/cy/sic-code-summary.json
- locales/en/sic-code-summary.json
- src/controllers/lp.before.you.file.controller.ts
- src/controllers/lp.check.your.answer.controller.ts
- src/controllers/lp.cs.date.controller.ts
- src/controllers/lp.sic.code.summary.controller.ts
- src/routes/routes.ts
- src/types/page.urls.ts
- src/types/template.paths.ts
- src/utils/session-navigation.ts
- test/controllers/lp.sic.code.summary.controller.unit.ts
- views/limited-partners/components/sic-code-summary/sic-code-summary.njk
**Ticket:** https://companieshouse.atlassian.net/browse/CSE-576
_Summary_
Sic Code Summary page created
Storing and retrieving previous page url in session
https://github.com/user-attachments/assets/66fdf9a4-4961-4696-9852-257b81f95034
> CSE-576 sic code summary

- src/controllers/lp.sic.code.summary.controller.ts
- src/routes/routes.ts
- src/types/page.urls.ts
- src/utils/session-navigation.ts
- test/controllers/lp.sic.code.summary.controller.unit.ts
- views/includes/scripts/lp.sic.code.script.js
- views/limited-partners/components/sic-code-summary/sic-code-summary.njk
**Ticket:** https://companieshouse.atlassian.net/browse/CSE-511
_Summary_
Add button disabled until something is entered in the text box
Add button adds and displays dummy data into the SIC code table
Remove button functionality
Tests for add/remove 
https://github.com/user-attachments/assets/5cacc0f2-89e4-43b6-803a-166e00754db1
> CSE-511 SIC code add remove

- locales/cy/lp-review.json
- locales/en/lp-review.json
- views/limited-partners/partials/lp-review.njk
- views/review.html
- fixed text
- removed spaces between checkbox
> CSE-541 : Update after QA findings 

- src/controllers/lp.sic.code.summary.controller.ts
> CSE-541: Updating review url 

- src/app.ts
- src/controllers/confirm.company.controller.ts
- src/types/page.urls.ts
- test/controllers/confirm.company.controller.unit.ts
- test/controllers/create.transaction.controller.unit.ts
- test/mocks/company.profile.mock.ts
- test/mocks/session.mock.ts
CSE-770 route lp company no acsp
> CSE-770 route lp company no acsp

- src/app.ts
- src/middleware/acsp.validation.middleware.ts
- src/middleware/company.authentication.middleware.ts
- test/controllers/lp.start.controller.unit.ts
- test/middleware/acsp.validation.middleware.unit.ts
- test/mocks/acsp.validation.middleware.mock.ts
- test/mocks/all.middleware.mock.ts
Ticket:
https://companieshouse.atlassian.net/browse/CSE-800
Changes:
- Add additional middleware for ACSP journey to check whether user is ACSP member or not
- Create unit test for ACSP middleware
- Update existing middleware mock to maintain existing unit test
> CSE-800: ACSP path interceptor

- src/controllers/lp.before.you.file.controller.ts
- src/controllers/lp.cs.date.controller.ts
- src/utils/session.acsp.ts
- test/controllers/lp.before.you.file.unit.ts
- test/utils/session.acsp.unit.ts
Create util to allow for values to be updated. Update checkbox value depending on if it's checked or not.
` 
console.log("DAVE --- " + getAcspSessionData(session)?.beforeYouFileCheck);
Default values before updating: 
DAVE --- false
After update:
DAVE --- true
`
> Before you file Session

- src/controllers/lp.check.your.answer.controller.ts
- test/controllers/lp.check.your.answer.unit.ts
‘Check Your Answers’ screen back button links back to the Confirmation Statement Date screen
Jira: https://companieshouse.atlassian.net/browse/CSE-783
https://github.com/user-attachments/assets/ad13dee2-74bb-4883-b98d-0604912f3f16
> Check your answer back button

- src/controllers/review.controller.ts
POST fix for issue seen in Test
Update previousPage in POST.
> POST fix for issue seen in Test

- locales/en/before-you-file.json
- test/controllers/lp.before.you.file.unit.ts
- test/middleware/acsp.validation.middleware.unit.ts
Updating wording missed in the most recent Mural, to allow QA to close off 627
> Cse 627 wording fix

- package-lock.json
run npm audit fix to correct dependency errors
> CSE-903 - run npm audit fix to correct dependency errors

- package-lock.json
- src/app.ts
- src/validators/lp.cs.date.validator.ts
Ticket:
https://companieshouse.atlassian.net/browse/CSE-895
Changes:
- run the `npm audit fix` for the solving vulnerability issue
> CSE-895: Fix the vulnerability issue

- package-lock.json
- package.json
Updates to resolve build issues in main.
> Typescript and Jest updates

- src/services/api.service.ts
Use INTERNAL_API_URL for Condensed SIC Code APIClient
> CSE-940 - Use INTERNAL_API_URL for Condensed SIC Code APIClient

- locales/cy/start.json
- locales/en/start.json
- src/controllers/start.controller.ts
- src/routes/routes.ts
- src/utils/feature.flag.ts
- src/utils/properties.ts
- test/global.setup.ts
- test/utils/feature.flag.unit.ts
- views/start.html
- add feature flag FEATURE_FLAG_SERVICE_WITHDRAWN_02102025
- update start page view:
- add top notification banner
- replace "Start now" button with action reminder
- update start page routes
- route all other paths to start page to prevent use of the service
> Add service withdrawn features to start page
