- test/controllers/company.number.controller.unit.ts
- test/controllers/confirm.company.controller.unit.ts
- test/controllers/error.controller.unit.ts
- test/controllers/start.controller.unit.ts
- test/middleware/service.availability.middleware.unit.ts
Noticed that we hadn't been clearing the mocks between tests which could cause issues in the future so added beforeEach blocks to clear them down.
> Clearing mocks between tests

- package.json
We should be explicit about the type of modules we import, ES modules are what we are using (as apposed to CommonJS with require) so setting that in the package.json . See https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_package_json_type_field for info.
> Setting package.json type field to load modules as ES modules

- src/app.ts
- src/controllers/error.controller.ts
- src/services/company.profile.service.ts
- src/utils/date.formatter.ts
- src/utils/logger.ts
- test/controllers/error.controller.unit.ts
- test/services/company.profile.service.unit.ts
- test/utils/date.formatter.unit.ts
To keep naming of the logger consistent I've changed it to be a named export instead of default.
> Making logger a named export to keep logger naming consistent

- jest.config.ts
Tests failed to run on nvm 12 and higher.
Fixed by using the newer style 'export' in jest.config and renamed it from .js to .ts
> Fix to make tests run on nvm v12 and higher

- jest.config.js
- package.json
reverting jest.config changes and removing the "types": "modules" from package.json to allow tests to run on all versions of nvm
> Fix tests for nvm v14

- src/controllers/trading.status.controller.ts
- test/controllers/trading.status.controller.unit.ts
- views/check-trading-status.html
Ticket updated with: For MVP we are not doing validation on the CORPORATE_BODY.COMPANY_TRADED_TYPE_ID thereofre the criterion is just to display the missing text.
> NCS-381 Trading status missing text

- test/controllers/confirm.company.controller.unit.ts
- views/paper-filing.html
Scottish paper filing companies SLP and SQP have differnet links on the CS01 stop page where :
Scottish limited partnership (SLP) should map to Limited partnership
Scottish qualifying partnership (SQP) should map to Scottish partnership
> NCS-389 Paper filing links need to vary on the stop page

- test/controllers/trading.status.controller.unit.ts
- views/check-trading-status.html
Checked thourgh the acceptance criteria and found that changes are needed for AC 5 only. Here we reintrodued the line added in NCS-381 minus the status checks as only those with code 0 CompanyTradedStatusType.NOT_ADMITTED_TO_TRADING will get to this page.
> NCS-404 Updated Trading Status Navigation

- test/controllers/confirm.company.controller.unit.ts
- views/invalid-company-status.html
The invalid company status stop screen wasn't showing the company name so this is to fix it.
> NCS-420 Add company name to invalid company status stop screen

- src/controllers/tasks/active.officers.controller.ts
- src/services/company.officers.service.ts
- src/utils/dummy.company.officers.ts
- src/utils/properties.ts
- test/controllers/tasks/active.officers.controller.unit.ts
- test/mocks/company.officers.mock.ts
- test/services/company.officers.service.unit.ts
Implement officer service to retrieve officers details from CH API 
Added feature flag due to lack of officer data in dev environments if true fetch will be made on officer data if false dummy officer data will be used. Config update is ready to be merged if this PR is approved
> NCS 446 retrieve officer details for active officer page 

- views/check-trading-status.html
- views/includes/continue-button.html
- views/tasks/active-officers.html
- views/tasks/active-pscs.html
- views/tasks/registered-office-address.html
- views/tasks/sic.html
- views/tasks/statement-of-capital.html
Add tracking event on Registered Office Address page.
Also refactored: Extracted "Continue" button to a file rather than have element duplicated across multiple pages.
> NCS-443 Matomo event tracking on ROA page.

- src/types/builders/confirmation.statement.submission.builder.ts
- test/types/builders/confirmation.statement.submission.builder.unit.ts
Adding a builder for creating confirmation statement submissions to keep the building in one place rather than in different controllers etc...
> NCS-282 Adding builder for confirmation statement submissions

- src/controllers/tasks/statement.of.capital.controller.ts
Update Statement of Capital controller to use cs submission builder. Haven't updated the tests as the builder is created using 'new' so don't think it can be mocked. Tests will continue to work as normal.
> NCS-480 Update SOC controller to use cs submission builder

- views/includes/officers.html
- views/includes/shareholders.html
Remove redundant code from the officers and shareholders page which was causing larger padding at the end of the row.
> NCS-554 Remove redundant code

- src/controllers/tasks/registered.office.address.controller.ts
- src/utils/constants.ts
- src/utils/url.ts
- test/controllers/tasks/registered.office.address.controller.unit.ts
- test/utils/url.unit.ts
Also, moved repeated URL-related functions that are repeated across multiple task pages to the _**utils/url.ts**_.
> NCS-551 Fix ROA page broken urls and address display on errorMsg render.

- package-lock.json
- package.json
RLE fields not present in version 1.43 so updated to 1.44
> NCS-135 Update private sdk to contain rle fields

- src/controllers/tasks/psc.statement.controller.ts
- src/utils/constants.ts
Adding the psc statement value to the cookie so that when we submit the page and there's an error, the psc statement can be retrieved to be displayed on the error page
> NCS-178 Adding psc statement value to cookie to redisplay on error page

- src/controllers/tasks/psc.statement.controller.ts
- src/utils/constants.ts
- test/controllers/tasks/psc.statement.controller.unit.ts
- test/mocks/person.of.significant.control.mock.ts
Some psc statements have a name placeholder that needs to be replaced with the name provided in the mongo record for psc statement
> NCS-611 Show psc name in statement

- src/controllers/tasks/people.with.significant.control.controller.ts
- src/controllers/tasks/psc.statement.controller.ts
- src/controllers/tasks/statement.of.capital.controller.ts
- test/controllers/tasks/people.with.significant.control.controller.unit.ts
- test/controllers/tasks/psc.statement.controller.unit.ts
- test/controllers/tasks/statement.of.capital.controller.unit.ts
- views/includes/task-list/people.html
Updating psc details page so that 'yes' and 'recent filing' filing buttons map to status of 'IN PROGRESS' (as psc statement is now the final page)
Making psc statement page retun to task list page with correct task list status.
> NCS-468 Updating task list status after psc statement page

- package-lock.json
- package.json
- src/controllers/tasks/people.with.significant.control.controller.ts
- test/controllers/tasks/people.with.significant.control.controller.unit.ts
Updating psc web controller to use the new dateOfBirthIso field on the psc data returned from the sdk in order to show the full DOB on the psc details screen.
> NCS-325 show full dob psc

- package-lock.json
- package.json
- src/services/transaction.service.ts
- test/services/transaction.service.unit.ts
Transaction api PUT doesn't return a body so removing check for resource body
> NCS-642 Removing check for resource on transaction api PUT

- src/controllers/tasks/registered.office.address.controller.ts
- src/utils/format.ts
The correct order of the address data to be displayed on web is;
> care_of
> po_box
> premises
> address_line_1
> address_line_2
> locality
> region
> country
> postal_code
> Fix address arrangement to march specified order in NCS-714

- views/tasks/statement-of-capital.html
[NCS-721
](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&modal=detail&selectedIssue=NCS-721)
Align radio button horizontally instead of vertically like in the prototype for statement of capital.
> NCS-721 Align radio button for statement of capital

- views/tasks/statement-of-capital.html
[NCS-721
](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-721)
Align the radio button on statement of capital page vertically instead of horizontally.
> NCS-721 Vertically align the radio button

- src/services/payment.service.ts
- test/services/payment.service.unit.ts
Adding a bit more info to the payment service log messages to highlight where the error occurred after we had some issues in testing and logs had 
{"created":"2021-11-08T14:58:09.068+00:00","event":"error","namespace":"Confirmation Statement Web","data":{"message":"400 - {\"message\":\"failed to execute http request\"}"}}
{"created":"2021-11-08T14:58:09.068+00:00","event":"error","namespace":"Confirmation Statement Web","data":{"message":"Error: Unknown Error {\"message\":\"failed to execute http request\"}\n    at createAndLogError
> Add module name to payment service log messages

- src/controllers/task.list.controller.ts
- src/controllers/trading.status.controller.ts
[BI-9484](https://companieshouse.atlassian.net/jira/software/c/projects/NCS/boards/234?modal=detail&selectedIssue=BI-9484)
Add template name to the render funciton of task list and trading status controllers so that the data events associated with it, is in the correct matomo event category.
> BI-9484 Add template name to task list and trading

- views/confirm-company.html
Removed from cs ui only - remains in the data as it is company profile data that predates the cs development.
> BI-9701 remove office address from confirm company page

- src/controllers/tasks/confirm.sic.code.controller.ts
- src/utils/constants.ts
- test/controllers/tasks/confirm.sic.code.controller.unit.ts
- views/incorrect-information/wrong-sic.html
Updating the page title of the SIC stop page to a title that has been provided by the user tracking team to help them track the users journey (matomo)
> BI-9954 Change page title of SIC stop page

- src/controllers/tasks/confirm.sic.code.controller.ts
- src/utils/constants.ts
- test/controllers/tasks/confirm.sic.code.controller.unit.ts
- views/incorrect-information/wrong-sic.html
Changing the SIC code stop page title to be hardcoded as there was no need for it to be parameterised
> BI-9954 hardcode the SIC stop page title

- views/tasks/shareholders.html
This was giving the radio element an h1 tag which was confusing screen readers.
> BI-10080 Removing isPageHeading option from shareholders page radio button element

- views/includes/natural-secretaries.html
- views/tasks/active-officers-details.html
Overriding the standard padding for that value to compress the table rows and match the prototype
> BI-10141 adding explicit padding on summary list values on officers details page

- views/tasks/active-officers-details.html
Empty rows were still being shown (with separator line) if the list was empty. 
Added a length check which also works if no list is passed to template
Added the missing list check to the (natural) directors row
https://stackoverflow.com/questions/37905073/check-if-an-object-is-empty-in-nunjucks
> BI-9960 Fix to only add officer row if list is present and not empty

- src/controllers/tasks/active.officers.details.controller.ts
- src/controllers/tasks/active.psc.details.controller.ts
- src/utils/format.ts
- test/controllers/tasks/active.psc.details.controller.unit.ts
- test/mocks/active.psc.details.controller.mock.ts
- views/tasks/active-psc-details.html
- views/tasks/includes/normal-psc.html
Updated template to use existing includes for individual psc and to add the other types.
Updated controller and based on the work completed for the active officer controller, reusing the existing formatting.
> BI-10288 Extract individual pscs and display

- test/mocks/person.of.significant.control.mock.ts
The mocked data didn't match the structure defined in PersonOfSignificantControl and was throwing a warning in test and wen you viewed the file in your IDE
> BI-10369 Fix mock data structure for mockPersonsOfSignificantControl

- src/utils/url.ts
Removing a debug statement that I added in the sanitiseReqlUrls. I hadn't truncated the value before logging.
These debugs were redundant anyway as the function called immediately after (sanitiseParam) also debugs out the param name (not value) so removing the extra ones I added.
> BI-10759 removing extra debug from sanitiseReqUrls

- src/utils/constants.ts
- src/utils/properties.ts
- src/utils/url.ts
- src/validators/radio.button.validator.ts
- src/validators/url.id.validator.ts
- test/global.setup.ts
- test/utils/url.unit.ts
Moving the validation constants to environment props aka config file.
Set default values as per the previous constants in case they are missing in config file
> BI-10757 Externalising the validation constants to config file

- src/app.ts
The companyAuth middleware will log the full url un-truncated if auth code is not recognised. So moving the param validation above it in the execution order to validate the url and query params first.
> BI-10762 Make param validation trigger before companyAuth

- src/controllers/tasks/active.officers.controller.ts
- src/controllers/tasks/active.officers.details.controller.ts
- src/controllers/tasks/active.psc.details.controller.ts
- src/controllers/tasks/psc.statement.controller.ts
- src/controllers/tasks/register.locations.controller.ts
- src/controllers/tasks/registered.office.address.controller.ts
- src/controllers/tasks/statement.of.capital.controller.ts
- test/controllers/tasks/active.directors.controller.unit.ts
- test/controllers/tasks/active.officers.details.controller.unit.ts
- test/controllers/tasks/active.psc.details.controller.unit.ts
- test/controllers/tasks/psc.statement.controller.unit.ts
- test/controllers/tasks/register.locations.controller.unit.ts
- test/controllers/tasks/registered.office.address.controller.unit.ts
- test/controllers/tasks/statement.of.capital.controller.unit.ts
- views/tasks/active-officers-details.html
- views/tasks/active-officers.html
- views/tasks/active-psc-details.html
- views/tasks/people-with-significant-control.html
- views/tasks/psc-statement.html
- views/tasks/register-locations.html
- views/tasks/registered-office-address.html
- views/tasks/shareholders.html
[BI-10663](https://companieshouse.atlassian.net/browse/BI-10663): Changed section_status (in confirmation_statement_submissions collection) updates from "confirmed" to "recent_filing" if the "No, but an update has been submitted" button is selected.
[BI-10813](https://companieshouse.atlassian.net/browse/BI-10813): Removed hard-coded header, and replaced it with an if-else block throwing out header depending on the number of shareholders. New header is in lowercase (shareholder/shareholders).
> Content changes for confirmation statement part 3

- src/utils/wrong.information.stop.screen.common.web.calls.ts
- test/controllers/incorrect-information/wrong.officer.details.controller.unit.ts
- test/controllers/incorrect-information/wrong.psc.details.controller.unit.ts
- test/controllers/incorrect-information/wrong.psc.statement.controller.unit.ts
- test/controllers/incorrect-information/wrong.registered.office.address.controller.unit.ts
- test/controllers/incorrect-information/wrong.registers.controller.unit.ts
Updated the section_status code sent to Mongo from "Confirmed" to "Recent_Filing" when the Yes radio button is clicked in the Stop screens. Updated respective unit tests accordingly.
[BI-11302](https://companieshouse.atlassian.net/browse/BI-11302)
> Updated section_status for Stop screens

- views/incorrect-information/wrong-details.html
- views/incorrect-information/wrong-registers.html
- views/incorrect-information/wrong-ro.html
Add Matomo tracking on Yes/No (wrong <s>ROA</s> MULTPLE pages)
Resolves:
+ Initially:
[BI-11340](https://companieshouse.atlassian.net/browse/BI-11340)
[BI-11363](https://companieshouse.atlassian.net/browse/BI-11363)
+  plus (by [rgoswami-ch](https://github.com/rgoswami-ch)) :
[BI-11392](https://companieshouse.atlassian.net/browse/BI-11392)
[BI-11393](https://companieshouse.atlassian.net/browse/BI-11393)
[BI-11394](https://companieshouse.atlassian.net/browse/BI-11394)
> Add Matomo tracking on Yes/No (wrong ROA page)

- src/controllers/incorrect-information/wrong.officer.details.controller.ts
- src/controllers/incorrect-information/wrong.psc.details.controller.ts
- src/controllers/incorrect-information/wrong.psc.statement.controller.ts
- src/controllers/incorrect-information/wrong.registers.controller.ts
- src/controllers/incorrect-information/wrong.shareholders.controller.ts
- src/controllers/start.controller.ts
- src/controllers/tasks/people.with.significant.control.controller.ts
- src/controllers/tasks/statement.of.capital.controller.ts
- src/controllers/trading.stop.controller.ts
- src/controllers/use.webfiling.controller.ts
- src/middleware/service.availability.middleware.ts
- src/utils/properties.ts
- test/global.setup.ts
- views/incorrect-information/wrong-details.html
- views/incorrect-information/wrong-registers.html
- views/incorrect-information/wrong-shareholders.html
- views/incorrect-information/wrong-sic.html
- views/incorrect-information/wrong-statement-of-capital.html
- views/service-offline.html
- views/start.html
- views/tasks/statement-of-capital.html
- views/trading-stop.html
- views/use-webfiling.html
Resolves:
https://companieshouse.atlassian.net/browse/BI-11403
Strip out `//seclogin?tc=1`
from EWF url, plus make it a config var
so that any change is just sourced via app_env
instead of needing a rebuild of 10 templates with a new artefact.
Linked to
https://github.com/companieshouse/chs-configs/pull/1949
> make EWF url a config var

- src/controllers/tasks/active.psc.details.controller.ts
- test/controllers/tasks/active.psc.details.controller.unit.ts
Changed `active.psc.details.controller` so that it doesn't `CHECKED` status until the user has completed the following screen. If the user uses the back button to go back to the task list after making a selection on the first screen, the status will now show `READ TO CONTINUE`.
Resolves: [BI-11341](https://companieshouse.atlassian.net/browse/BI-11341)
> Bugfix incorrect checked status

- src/controllers/confirmation.controller.ts
- views/confirmation.html
- views/includes/signout-bar.html
- views/layout.html
Added signout bar to confirmation screen. 
Added configuration to signout bar to allow signout url to change.
In the confirmation controller, set the signoutURL so that the signout cofirmation screen is by passed. 
Addition to [BI-11289](https://companieshouse.atlassian.net/browse/BI-11289)
> Signout - Add signout to confirmation screen

- views/includes/signout-bar.html
- views/layout.html
Added the CSS stylesheet to the layout.html.
Added the JavaScript file to the signout-bar.html, so that the users are only timed out if they are signed in.
Resolves:
- BI-12077
> changes to signout bar and layout for timeout

- terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
Matches cidev ECS to cidev mesos based on environment var kept here:
https://github.com/companieshouse/chs-configs/blob/develop/cidev/confirmation-statement-web/env
> Update log_level to match mesos cidev

- src/controllers/tasks/confirm.email.address.controller.ts
- src/utils/constants.ts
- test/controllers/tasks/confirm.email.address.controller.unit.ts
Two parallel pieces of work added different constants with the same value - switching to use EMAIL consistently and removing REA.
> Use SECTION.EMAIL for all email status updates

- views/includes/other-ways-to-file.html
- views/paper-filing.html
- views/start.html
Update paper fee amount from £40 to £62 (in service unavailable page as well as start page).
Also update all instances of paper form link (start page, service unavailable page, paper filing page) to point to post-ECCT version.
> Update paper fee amount & paper form url [BI-13955]

- package-lock.json
- package.json
Web security node library already present so upgraded from 4.2.0 to the latest as of today 4.3.1
> SEC-111 Upgraded to latest web security node

- package-lock.json
- package.json
Problems with pipeline deployment to cidev, error found int he logs:
"Could not handle CSRF validation: TypeError: Cannot read properties of undefined (reading 'length')"
Similar problem found in registered email address: https://github.com/companieshouse/registered-email-address-web/pull/177/files
So applied the same upgrade fix here.
> SEC-113 Upgrade web security node module

- src/controllers/lp.sic.code.summary.controller.ts
- test/controllers/lp.sic.code.summary.controller.unit.ts
The back button links back to either the 'Confirmation Statement Date' screen or the 'Check Your Answers' screen dependent on whether or not a alternate Confirmation Date was provided
JIRA: https://companieshouse.atlassian.net/browse/CSE-784
https://github.com/user-attachments/assets/b7be9f6f-ebb3-4803-84ce-c1832e19cfc8
> CSE-784 Check SIC Codes Back Button

- src/controllers/confirm.company.controller.ts
- src/utils/feature.flag.ts
- src/utils/limited.partnership.ts
- test/controllers/confirm.company.controller.unit.ts
- test/utils/feature.flag.unit.ts
Ticket:
https://companieshouse.atlassian.net/browse/CSE-839
Changes:
- Since [ticket 838](https://companieshouse.atlassian.net/browse/CSE-838) created new subtype field, the logic need to be updated to satisfy the AC of [the ticket 839](https://companieshouse.atlassian.net/browse/CSE-839)
- Created the unit test for `shouldRedirectToPaperFilingForInvalidLp` function
- rename the function `isScottishPrivateFundimitedPartnershipFeatureEnabled` to `isScottishPrivateFundLimitedPartnershipFeatureEnabled`
> CSE-839: Put LP subtypes behind feature flags v2

- src/controllers/lp.before.you.file.controller.ts
- test/controllers/lp.before.you.file.unit.ts
- test/middleware/acsp.validation.middleware.unit.ts
- views/limited-partners/components/before-you-file/before-you-file.njk
https://companieshouse.atlassian.net/browse/CSE-649
Conditionally showing payment related text on before you file screen
Add **isPaymentDue** logic to **Before You File** controller and view
- Integrated isPaymentDue(transaction, submissionId) into the GET handler to conditionally render payment-related messaging.
- Updated Nunjucks template to display fee information when payment is due.
- Added unit tests to cover both true and false cases for isPaymentDue.
- Refactored controller to support error handling 
**When payment is due**
**When payment is not due**
> CSE-649 : BYF conditional payment message

- package.json
updated api-sdk-node version to 2.0.283 for optional CompayProfile.subtype
> CSE-895 - updated api-sdk-node version to 2.0.283 for optional CompayProfile.subtype

- package-lock.json
updated package-lock.json for v2.0.283 of api-sdk-node
> CSE-895 - updated package-lock.json for v2.0.283 of api-sdk-node
